x-environment:
  &default-back-environment
  # Database settings
  OURCHIVE_DB_NAME: "${OURCHIVE_DB_NAME}"
  OURCHIVE_DB_USER: "${OURCHIVE_DB_USER}"
  OURCHIVE_DB_PASSWORD: "${OURCHIVE_DB_PW}"
  OURCHIVE_DB_HOST: "${OURCHIVE_DB_HOST}"
  # Web settings
  SECRET_KEY: "${OURCHIVE_SECRET_KEY}"
  OURCHIVE_SITES_SCHEME: "${OURCHIVE_SCHEME}"
  OURCHIVE_SECRET_KEY: "${OURCHIVE_SECRET_KEY}"
  OURCHIVE_DB_PW: "${OURCHIVE_DB_PW}"
  OURCHIVE_INTEGRATION_DB_NAME: "${OURCHIVE_INTEGRATION_DB_NAME}"
  OURCHIVE_DB_PORT: "${OURCHIVE_DB_PORT}"
  OURCHIVE_DEBUG: "${OURCHIVE_DEBUG}"
  OURCHIVE_DEV: "${OURCHIVE_DEV}"
  OURCHIVE_MAILGUN_API_KEY: "${OURCHIVE_MAILGUN_API_KEY}"
  OURCHIVE_MEDIA_ROOT: "${OURCHIVE_MEDIA_ROOT}"
  OURCHIVE_MEDIA_URL: "${OURCHIVE_MEDIA_URL}"
  OURCHIVE_SCRIPTS_ROOT: "${OURCHIVE_SCRIPTS_ROOT}"
  OURCHIVE_SCHEME: "${OURCHIVE_SCHEME}"
  OURCHIVE_DOMAIN: "${OURCHIVE_DOMAIN}"
  OURCHIVE_TMP_ROOT: "${OURCHIVE_TMP_ROOT}"
  OURCHIVE_CAPTCHA_SITE_KEY: "${OURCHIVE_CAPTCHA_SITE_KEY}"
  OURCHIVE_USE_CAPTCHA: "${OURCHIVE_USE_CAPTCHA}"
  OURCHIVE_CAPTCHA_PROVIDER: "${OURCHIVE_CAPTCHA_PROVIDER}"
  OURCHIVE_CAPTCHA_PARAM: "${OURCHIVE_CAPTCHA_PARAM}"
  OURCHIVE_CAPTCHA_SECRET: "${OURCHIVE_CAPTCHA_SECRET}"
  OURCHIVE_ROOT_URL: "${OURCHIVE_ROOT_URL}"
  OURCHIVE_MAILGUN_SENDER_DOMAIN: "${OURCHIVE_MAILGUN_SENDER_DOMAIN}"
  OURCHIVE_SERVER_IP: "${OURCHIVE_SERVER_IP}"
  OURCHIVE_SERVER_EMAIL: "${OURCHIVE_SERVER_EMAIL}"
  OURCHIVE_DEFAULT_FROM_EMAIL: "${OURCHIVE_DEFAULT_FROM_EMAIL}"
  OURCHIVE_LOG_LEVEL: "${OURCHIVE_LOG_LEVEL}"
  OURCHIVE_S3_SECRET_KEY: "${OURCHIVE_S3_SECRET_KEY}"
  OURCHIVE_S3_SECRET_ACCESS_KEY: "${OURCHIVE_S3_SECRET_ACCESS_KEY}"
  OURCHIVE_S3_ENDPOINT_URL: "${OURCHIVE_S3_ENDPOINT_URL}"
  OURCHIVE_S3_BUCKET: "${OURCHIVE_S3_BUCKET}"
  OURCHIVE_FILE_PROCESSOR: "${OURCHIVE_FILE_PROCESSOR}"
  OURCHIVE_S3_ENDPOINT_PROTOCOL: "${OURCHIVE_S3_ENDPOINT_PROTOCOL}"
  OURCHIVE_DOCKER: "${OURCHIVE_DOCKER}"
  OURCHIVE_SUPERUSER_NAME: "${OURCHIVE_SUPERUSER_NAME}"
  OURCHIVE_SUPERUSER_EMAIL: "${OURCHIVE_SUPERUSER_EMAIL}"
  OURCHIVE_SUPERUSER_PASSWORD: "${OURCHIVE_SUPERUSER_PASSWORD}"
  # Email settings.
  # EMAIL_BACKEND: "django.core.mail.backends.${EMAIL_BACKEND}.EmailBackend"
  # DEFAULT_FROM_EMAIL: "${EMAIL_DEFAULT_FROM}"
  # EMAIL_USE_TLS: "${EMAIL_USE_TLS}"
  # EMAIL_USE_SSL: "${EMAIL_USE_SSL}"
  # EMAIL_HOST: "${EMAIL_HOST}"
  # EMAIL_PORT: "${EMAIL_PORT}"
  # EMAIL_HOST_USER: "${EMAIL_HOST_USER}"
  # EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD}"

x-volumes:
  &default-back-volumes
  - ourchive-static-data:/ourchive_app/static
  - ourchive-media-data:/ourchive_app/media

services:
  ourchive-db:
    image: postgres:16.8
    environment:
      POSTGRES_DB: "${OURCHIVE_DB_NAME}"
      POSTGRES_USER: "${OURCHIVE_DB_USER}"
      POSTGRES_PASSWORD: "${OURCHIVE_DB_PW}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${OURCHIVE_DB_USER}"]
      interval: 2s
      timeout: 15s
      retries: 5
      start_period: 3s
    volumes:
      - ourchive-db-data:/var/lib/postgresql/data
    networks:
      - ourchive

  ourchive:
    #image: ourchiveio/ourchive:latest
    image: ourchive
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - ourchive
    depends_on:
      ourchive-db:
        condition: service_healthy

  ourchive-gateway:
    image: nginx:1.19-alpine
    ports:
      - "9000:80"
    volumes:
      - ./ourchive-gateway/ourchive.conf:/etc/nginx/conf.d/default.conf
      - ourchive-static-data:/ourchive/static
      - ourchive-media-data:/ourchive/media
    networks:
      - ourchive
    depends_on:
      - ourchive

volumes:
  ourchive-static-data:
  ourchive-media-data:
  ourchive-db-data:

networks:
  ourchive: